stages:
  - test
  - pages
  - deploy

test:
  tags:
    - docker
  image: continuumio/miniconda3:4.10.3 
  stage: test
  before_script:
  script:
    - conda env create -f environment_linux.yml
    - conda init bash
    - source ~/.bashrc
    - conda activate hazmaps
  #  - cd hazardmaps
    - echo $PWD
    - export PYTHONPATH=.
    - pytest --mpl -vvs test/test.py

pages:
  image: continuumio/miniconda3:4.10.3 
  stage: pages
  script:
  - conda create -n pages
  - conda install -y sphinx -n pages
  - conda install -y sphinx_rtd_theme -n pages
  - conda init bash
  - source ~/.bashrc
  - conda activate pages
  - sphinx-build -b html -c ./docs docs public
  artifacts:
    paths:
    - public
  only:
  - master

