stages:
  - test
  - pages
  - deploy

test:
  tags:
    - docker
  image: continuumio/miniconda3:4.10.3 
  stage: test
  before_script:
  script:
    - conda env create -f environment.yml
    - conda init bash
    - source ~/.bashrc
    - conda activate hazmap
    - cd hazardmaps
    - echo $PWD
    - export PYTHONPATH=.
    - pytest --mpl -vvs test.py

pages-build:
  stage: pages
  script:
  - pip install -U sphinx
  - sphinx-build -b html . docs
  only:
  - branches
  except:
  - master

pages:
  stage: pages
  script:
  - pip install -U sphinx
  - sphinx-build -b html . docs
  artifacts:
    paths:
    - docs
  only:
  - master
