# packages in environment at /home/decval/anaconda3/envs/sci-basic:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda/main
_openmp_mutex             4.5                       1_gnu    conda/main
affine                    2.3.0              pyhd3eb1b0_0    conda/main
argon2-cffi               20.1.0           py38h27cfd23_1    conda/main
async_generator           1.10               pyhd3eb1b0_0    conda/main
attrs                     21.2.0             pyhd3eb1b0_0    conda/main
aws-c-common              0.4.57               he6710b0_1    conda/main
aws-c-event-stream        0.1.6                h2531618_5    conda/main
aws-checksums             0.1.9                he6710b0_0    conda/main
aws-sdk-cpp               1.8.185              hce553d0_0    conda/main
backcall                  0.2.0              pyhd3eb1b0_0    conda/main
blas                      1.0                         mkl    conda/main
bleach                    4.0.0              pyhd3eb1b0_0    conda/main
bottleneck                1.3.2            py38heb32a55_1    conda/main
brotli                    1.0.9                he6710b0_2    conda/main
bzip2                     1.0.8                h7b6447c_0    conda/main
c-ares                    1.17.1               h27cfd23_0    conda/main
ca-certificates           2021.7.5             h06a4308_1    conda/main
cairo                     1.16.0               hf32fb01_1    conda/main
certifi                   2021.5.30        py38h06a4308_0    conda/main
cffi                      1.14.6           py38h400218f_0    conda/main
cfitsio                   3.470                hf0d0db6_6    conda/main
click                     7.1.2              pyhd3eb1b0_0    conda/main
click-plugins             1.1.1              pyhd3eb1b0_0    conda/main
cligj                     0.7.2            py38h06a4308_0    conda/main
curl                      7.78.0               h1ccaba5_0    conda/main
cycler                    0.10.0                   py38_0    conda/main
dbus                      1.13.18              hb2f20db_0    conda/main
decorator                 5.0.9              pyhd3eb1b0_0    conda/main
defusedxml                0.7.1              pyhd3eb1b0_0    conda/main
descartes                 1.1.0                      py_4    https://conda.anaconda.org/conda-forge
entrypoints               0.3                      py38_0    conda/main
expat                     2.4.1                h2531618_2    conda/main
fiona                     1.8.13.post1     py38hc820daa_0    conda/main
fontconfig                2.13.1               h6c09931_0    conda/main
fonttools                 4.25.0             pyhd3eb1b0_0    conda/main
freetype                  2.10.4               h5ab3b9f_0    conda/main
freexl                    1.0.6                h27cfd23_0    conda/main
gdal                      3.0.2            py38h4694593_1    conda/main
geopandas                 0.8.1                      py_0  
geos                      3.8.0                he6710b0_0    conda/main
geotiff                   1.6.0                h21e8280_0    conda/main
giflib                    5.2.1                h7b6447c_0    conda/main
glib                      2.69.1               h5202010_0    conda/main
gst-plugins-base          1.14.0               h8213a91_2    conda/main
gstreamer                 1.14.0               h28cd5cc_2    conda/main
hdf4                      4.2.13               h3ca952b_2    conda/main
hdf5                      1.10.6               hb1b8bf9_0    conda/main
icu                       58.2                 he6710b0_3    conda/main
importlib-metadata        3.10.0           py38h06a4308_0    conda/main
importlib_metadata        3.10.0               hd3eb1b0_0    conda/main
iniconfig                 1.1.1              pyhd3eb1b0_0    conda/main
intel-openmp              2021.3.0          h06a4308_3350    conda/main
ipykernel                 5.3.4            py38h5ca1d4c_0    conda/main
ipython                   7.16.1           py38h5ca1d4c_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1    conda/main
ipywidgets                7.6.3              pyhd3eb1b0_1    conda/main
jedi                      0.18.0           py38h06a4308_1    conda/main
jinja2                    3.0.1              pyhd3eb1b0_0    conda/main
jpeg                      9b                   h024ee3a_2    conda/main
json-c                    0.13.1               h1bed415_0    conda/main
jsonschema                3.2.0              pyhd3eb1b0_2    conda/main
jupyter                   1.0.0                    py38_7  
jupyter_client            7.0.1              pyhd3eb1b0_0    conda/main
jupyter_console           6.4.0              pyhd3eb1b0_0    conda/main
jupyter_core              4.7.1            py38h06a4308_0    conda/main
jupyterlab_pygments       0.1.2                      py_0    conda/main
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    conda/main
kealib                    1.4.14               h54c064f_0    conda/main
kiwisolver                1.3.1            py38h2531618_0    conda/main
krb5                      1.19.2               hac12032_0    conda/main
lcms2                     2.12                 h3be6417_0    conda/main
ld_impl_linux-64          2.35.1               h7274673_9    conda/main
libboost                  1.73.0              h3ff78a5_11    conda/main
libcurl                   7.78.0               h0b77cf5_0    conda/main
libdap4                   3.19.1               h6ec2957_0    conda/main
libedit                   3.1.20210714         h7f8727e_0    conda/main
libev                     4.33                 h7b6447c_0    conda/main
libffi                    3.3                  he6710b0_2    conda/main
libgcc-ng                 9.3.0               h5101ec6_17    conda/main
libgdal                   3.0.2                h7c14f60_1    conda/main
libgfortran-ng            7.5.0               ha8ba4b0_17    conda/main
libgfortran4              7.5.0               ha8ba4b0_17    conda/main
libgomp                   9.3.0               h5101ec6_17    conda/main
libkml                    1.3.0                h7ecb851_5    conda/main
libnetcdf                 4.6.1                h2053bdc_4    conda/main
libnghttp2                1.41.0               hf8bcb03_2    conda/main
libpng                    1.6.37               hbc83047_0    conda/main
libpq                     12.2                 h553bfba_1    conda/main
libsodium                 1.0.18               h7b6447c_0    conda/main
libspatialindex           1.9.3                h2531618_0    conda/main
libspatialite             4.3.0a               h793db0d_0    conda/main
libssh2                   1.9.0                h1ba5d50_1    conda/main
libstdcxx-ng              9.3.0               hd4cf53a_17    conda/main
libtiff                   4.2.0                h85742a9_0    conda/main
libuuid                   1.0.3                h1bed415_2    conda/main
libwebp-base              1.2.0                h27cfd23_0    conda/main
libxcb                    1.14                 h7b6447c_0    conda/main
libxml2                   2.9.12               h03d6c58_0    conda/main
lz4-c                     1.9.3                h295c915_1    conda/main
markupsafe                2.0.1            py38h27cfd23_0    conda/main
matplotlib                3.4.2            py38h06a4308_0    conda/main
matplotlib-base           3.4.2            py38hab158f2_0    conda/main
mistune                   0.8.4           py38h7b6447c_1000    conda/main
mkl                       2021.3.0           h06a4308_520    conda/main
mkl-service               2.4.0            py38h7f8727e_0    conda/main
mkl_fft                   1.3.0            py38h42c9631_2    conda/main
mkl_random                1.2.2            py38h51133e4_0    conda/main
more-itertools            8.8.0              pyhd3eb1b0_0    conda/main
munch                     2.5.0              pyhd3eb1b0_0    conda/main
munkres                   1.1.4                      py_0    conda/main
nbclient                  0.5.3              pyhd3eb1b0_0    conda/main
nbconvert                 6.1.0            py38h06a4308_0    conda/main
nbformat                  5.1.3              pyhd3eb1b0_0    conda/main
ncurses                   6.2                  he6710b0_1    conda/main
nest-asyncio              1.5.1              pyhd3eb1b0_0    conda/main
notebook                  6.4.3            py38h06a4308_0    conda/main
numexpr                   2.7.3            py38h22e1b3c_1    conda/main
numpy                     1.20.3           py38hf144106_0    conda/main
numpy-base                1.20.3           py38h74d4b33_0    conda/main
olefile                   0.46               pyhd3eb1b0_0    conda/main
openjpeg                  2.4.0                h3ad879b_0    conda/main
openssl                   1.1.1l               h7f8727e_0    conda/main
packaging                 21.0               pyhd3eb1b0_0    conda/main
pandas                    1.3.2            py38h8c16a72_0    conda/main
pandocfilters             1.4.3            py38h06a4308_1    conda/main
parso                     0.8.2              pyhd3eb1b0_0    conda/main
pcre                      8.45                 h295c915_0    conda/main
pexpect                   4.8.0              pyhd3eb1b0_3    conda/main
pickleshare               0.7.5           pyhd3eb1b0_1003    conda/main
pillow                    8.3.1            py38h2c7a002_0    conda/main
pip                       21.2.2           py38h06a4308_0    conda/main
pixman                    0.40.0               h7b6447c_0    conda/main
pluggy                    0.13.1           py38h06a4308_0    conda/main
poppler                   0.81.0               h01f5e8b_2    conda/main
poppler-data              0.4.10               h06a4308_0    conda/main
postgresql                12.2                 h553bfba_1    conda/main
proj                      6.2.1                haa6030c_0    conda/main
prometheus_client         0.11.0             pyhd3eb1b0_0    conda/main
prompt-toolkit            3.0.17             pyhca03da5_0    conda/main
prompt_toolkit            3.0.17               hd3eb1b0_0    conda/main
ptyprocess                0.7.0              pyhd3eb1b0_2    conda/main
py                        1.10.0             pyhd3eb1b0_0    conda/main
pycparser                 2.20                       py_2    conda/main
pygments                  2.10.0             pyhd3eb1b0_0    conda/main
pyparsing                 2.4.7              pyhd3eb1b0_0    conda/main
pyproj                    2.6.1.post1      py38hb3025e9_1    conda/main
pyqt                      5.9.2            py38h05f1152_4    conda/main
pyrsistent                0.17.3           py38h7b6447c_0    conda/main
pytest                    6.2.4            py38h06a4308_2    conda/main
pytest-mpl                0.13                     pypi_0    pypi
python                    3.8.11          h12debd9_0_cpython    conda/main
python-dateutil           2.8.2              pyhd3eb1b0_0    conda/main
pytz                      2021.1             pyhd3eb1b0_0    conda/main
pyzmq                     22.2.1           py38h295c915_1    conda/main
qt                        5.9.7                h5867ecd_1    conda/main
qtconsole                 5.1.0              pyhd3eb1b0_0    conda/main
qtpy                      1.10.0             pyhd3eb1b0_0    conda/main
rasterio                  1.1.2            py38h900e953_0    https://conda.anaconda.org/conda-forge
readline                  8.1                  h27cfd23_0    conda/main
rtree                     0.9.7            py38h06a4308_1    conda/main
send2trash                1.5.0              pyhd3eb1b0_1    conda/main
setuptools                52.0.0           py38h06a4308_0    conda/main
shapely                   1.7.1            py38h98ec03d_0    conda/main
sip                       4.19.13          py38he6710b0_0    conda/main
six                       1.16.0             pyhd3eb1b0_0    conda/main
snuggs                    1.4.7              pyhd3eb1b0_0    conda/main
sqlite                    3.36.0               hc218d9a_0    conda/main
terminado                 0.9.4            py38h06a4308_0    conda/main
testpath                  0.5.0              pyhd3eb1b0_0    conda/main
tiledb                    2.2.9                hffe1d7a_0    conda/main
tk                        8.6.10               hbc83047_0    conda/main
toml                      0.10.2             pyhd3eb1b0_0    conda/main
tornado                   6.1              py38h27cfd23_0    conda/main
traitlets                 5.0.5              pyhd3eb1b0_0    conda/main
wcwidth                   0.2.5              pyhd3eb1b0_0    conda/main
webencodings              0.5.1                    py38_1    conda/main
wheel                     0.37.0             pyhd3eb1b0_1    conda/main
widgetsnbextension        3.5.1                    py38_0    conda/main
xerces-c                  3.2.3                h780794e_0    conda/main
xz                        5.2.5                h7b6447c_0    conda/main
zeromq                    4.3.4                h2531618_0    conda/main
zipp                      3.5.0              pyhd3eb1b0_0    conda/main
zlib                      1.2.11               h7b6447c_3    conda/main
zstd                      1.4.9                haebb681_0    conda/main
