
name: hazmaps
channels:
  - conda/main
  - defaults
  - https://nexus-internal.bgs.ac.uk/repository/conda/main
  - https://nexus-internal.bgs.ac.uk/repository/conda-forge
dependencies:
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.5
  - curl=7.85.0
  - cycler=0.11.0
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - fiona=1.8.13.post1
  - fonttools=4.25.0
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.0.2
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.8.0
  - geotiff=1.7.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - intel-openmp=2021.4.0
  - ipython=8.4.0
  - jedi=0.18.1
  - joblib=1.1.1
  - jpeg=9e
  - kealib=1.4.14
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.85.0
  - libdeflate=1.8
  - libgdal=3.0.2
  - libiconv=1.16
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=12.9
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libzip=1.8.0
  - lz4-c=1.9.3
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mapclassify=2.4.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - munkres=1.1.4
  - networkx=2.8.4
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - proj=6.2.1
  - prompt-toolkit=3.0.20
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.9
  - pyproj=2.6.1.post1
  - python=3.9.13
  - python-dateutil=2.8.2
  - pytz=2022.1
  - rtree=0.9.7
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - setuptools=65.5.0
  - shapely=1.8.4
  - six=1.16.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - threadpoolctl=2.2.0
  - tiledb=2.3.3
  - tk=8.6.12
  - traitlets=5.1.1
  - tzdata=2022f
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wincertstore=0.2
  - xerces-c=3.2.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2