name: hazmaps
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=21.2.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - curl=7.79.1
  - cycler=0.10.0
  - decorator=4.4.2
  - expat=2.4.1
  - fiona=1.8.20
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.3.2
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=68.1
  - iniconfig=1.1.1
  - jbig=2.1
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.15
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgdal=3.3.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - matplotlib-base=3.4.3
  - more-itertools=8.10.0
  - munch=2.5.0
  - ncurses=6.2
  - networkx=2.6.3
  - numpy=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.3
  - pcre=8.45
  - pillow=8.3.2
  - pip=21.2.4
  - pixman=0.40.0
  - pluggy=1.0.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.0.1
  - pthread-stubs=0.4
  - py=1.10.0
  - pyparsing=2.4.7
  - pyproj=3.2.1
  - pytest=6.2.5
  - pytest-mpl=0.13
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - readline=8.1
  - rtree=0.9.7
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - setuptools=58.0.4
  - shapely=1.7.1
  - six=1.16.0
  - sqlite=3.36.0
  - threadpoolctl=2.2.0
  - tiledb=2.3.4
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - tzcode=2021a
  - tzdata=2021a
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
